### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by dracemix** [ninevra/Simple-Temporary-Containers#4]
I went to install on FF 55.0 and the following problem occurs.

This extension cannot be installed because it seems
be damaged.

How can I install it?

**Comment by SchnWalter** [comment]
As I said, the old extensions API has been replaced in the Firefox Quantum (v57) release in November 2017. So, there is no way to use this extension, created in October 2019, on browsers that use the old API.

P.S. You can open as many issues as you want (https://github.com/sagitta1618/temporaryTabContainer/issues/10), there's no way to have temporary containers in the old Firefox releases. At best, you could write some scripts to have temporary profiles; good luck.

**Comment by ninevra** [comment]
@dracemix This extension isn't compatible with Firefox v55, as it relies on APIs introduced in Firefox v57 and possibly later versions.

It might be possible to make it partially work on older versions by [manually enabling the contextualIdentities feature](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities) by setting `privacy.userContext.enabled` preference to `true` in `about:config`. However, I unfortunately don't have the ability to test with or provide support for out-of-date versions of Firefox. I recommend you update to a current version of Firefox and look for an alternative for the other extension you mentioned.
