### ISSUE TITLE
Prevent making permanent

### ISSUE THREAD

**Issue by ghost** [ninevra/Simple-Temporary-Containers#5]
Is there a way to prevent making the containers permanent or the api of firefox enforces this as a feature?

I can see a few scenarios where it's not desired to be able to do so.

**Comment by ninevra** [comment]
Hi infosisio! Could you clarify what you mean by "making the containers permanent"? By default the containers created by this extension should be temporary, meaning they should be deleted automatically once all their tabs are closed. They should only become permanent if you manually rename them.

Are you encountering containers persisting after their tabs are closed? Or are you saying you'd like to be able to rename temporary containers without making them permanent?
